name: nested 1

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  call-another-reusable:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: joshjohanning-org/nested-reusable-workflows/.github/workflows/nested2.yml@main
