name: nested 1

on:
  workflow_call:

jobs:
  call-another-reusable:
    uses: joshjohanning-org/nested-reusable-workflows/.github/workflows/nested2.yml@main
  example_job2:
    name: Generate output
    runs-on: arc-runner-set
    steps:
      - id: step1
        run: echo "test"
