name: nested 1

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: ${{ vars.PYTHON_VERSION }}

jobs:
  call:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: ./.github/workflows/nested2.yml

  two:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi ${{ inputs.python-version }}"
      
