name: nested 1

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  call:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: ./.github/workflows/nested2.yml
