name: nested 2

on:
  workflow_call:

jobs:
  call-another-reusable:
    uses: ./.github/workflows/nested3.yml
  example_job:
    name: out-2
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test"
