name: nested 3

on:
  workflow_call:

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test"
  call-another-reusable:
    uses: joshjohanning-org/nested-reusable-workflows/.github/workflows/nested2.yml@main