name: nested 2

on:
  workflow_call:

jobs:
  call-another-reusable:
    uses: joshjohanning-org/nested-reusable-workflows/.github/workflows/nested3.yml@main
  example_job:
    name: Generate output - diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - id: step1
        run: echo "test"
